steps:
  # 1. Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/atlas/backend-worker', '-f', 'Dockerfile.backend', '.']
    
  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/atlas/backend-worker']
    
  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'atlas-worker'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/atlas/backend-worker'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,REDIS_URL=redis://10.82.159.155:6379'
      - '--vpc-connector'
      - 'atlas-vpc-con'
      
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/atlas/backend-worker'
