CREATE TABLE `airway_bills` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text DEFAULT 'DIRECT' NOT NULL,
	`awb_number` text NOT NULL,
	`airline_prefix` text,
	`airline_name` text,
	`parent_mawb_id` text,
	`origin_airport` text DEFAULT 'MAD' NOT NULL,
	`destination_airport` text DEFAULT 'JFK' NOT NULL,
	`flight_number` text,
	`flight_date` integer,
	`shipper_data` text,
	`consignee_data` text,
	`issuing_agent_data` text,
	`pieces` integer DEFAULT 1 NOT NULL,
	`gross_weight_kg` real DEFAULT 0 NOT NULL,
	`volume_cbm` real DEFAULT 0 NOT NULL,
	`volumetric_weight_kg` real DEFAULT 0 NOT NULL,
	`chargeable_weight_kg` real DEFAULT 0 NOT NULL,
	`rate_class` text DEFAULT 'N' NOT NULL,
	`rate_per_kg` real DEFAULT 0 NOT NULL,
	`freight_charge` real DEFAULT 0 NOT NULL,
	`other_charges` text,
	`total_prepaid` real DEFAULT 0 NOT NULL,
	`total_collect` real DEFAULT 0 NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`nature_of_goods` text DEFAULT 'General Cargo' NOT NULL,
	`special_handling_codes` text,
	`dgr_details` text,
	`handling_info` text,
	`status` text DEFAULT 'DRAFT' NOT NULL,
	`e_awb_certified` integer DEFAULT true NOT NULL,
	`awb_data` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `airway_bills_awb_number_unique` ON `airway_bills` (`awb_number`);--> statement-breakpoint
CREATE TABLE `dgr_registry` (
	`un_number` text PRIMARY KEY NOT NULL,
	`proper_shipping_name` text NOT NULL,
	`dgr_class` text NOT NULL,
	`sub_risks` text,
	`packing_group` text,
	`passenger_limit_kg` text DEFAULT 'FORBIDDEN' NOT NULL,
	`cargo_aircraft_limit_kg` text DEFAULT '35 kg' NOT NULL,
	`packing_instruction_pax` text,
	`packing_instruction_cao` text,
	`default_shc` text DEFAULT 'DGR' NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
--> statement-breakpoint
CREATE TABLE `iata_airports` (
	`code` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`city` text NOT NULL,
	`country_code` text NOT NULL,
	`timezone` text DEFAULT 'UTC' NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
