CREATE TABLE `commercial_contracts` (
	`id` text PRIMARY KEY NOT NULL,
	`contract_number` text NOT NULL,
	`title` text NOT NULL,
	`seller_company_id` text,
	`buyer_company_id` text,
	`seller_data` text,
	`buyer_data` text,
	`forwarder_data` text,
	`incoterm_code` text NOT NULL,
	`named_place` text NOT NULL,
	`transport_mode` text DEFAULT 'MULTIMODAL' NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`goods_value` real NOT NULL,
	`freight_estimated_cost` real DEFAULT 0 NOT NULL,
	`insurance_estimated_cost` real DEFAULT 0 NOT NULL,
	`customs_estimated_duty` real DEFAULT 0 NOT NULL,
	`effective_date` integer NOT NULL,
	`expiry_date` integer,
	`status` text DEFAULT 'ACTIVE' NOT NULL,
	`governing_law` text DEFAULT 'ICC / Spanish Commercial Code' NOT NULL,
	`dispute_jurisdiction` text DEFAULT 'Arbitration Tribunal Madrid' NOT NULL,
	`milestones_data` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `commercial_contracts_contract_number_unique` ON `commercial_contracts` (`contract_number`);--> statement-breakpoint
CREATE TABLE `incoterm_rules` (
	`code` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`transport_category` text NOT NULL,
	`risk_transfer_point` text NOT NULL,
	`cost_transfer_point` text NOT NULL,
	`insurance_requirement` text NOT NULL,
	`seller_responsibilities` text,
	`buyer_responsibilities` text,
	`customs_export_by` text DEFAULT 'SELLER' NOT NULL,
	`customs_import_by` text DEFAULT 'BUYER' NOT NULL,
	`description` text NOT NULL,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
