CREATE TABLE `cargo_claims` (
	`id` text PRIMARY KEY NOT NULL,
	`claim_number` text NOT NULL,
	`shipment_id` text,
	`transport_doc_number` text NOT NULL,
	`transport_mode` text NOT NULL,
	`governing_convention` text NOT NULL,
	`incident_type` text NOT NULL,
	`incident_date` integer NOT NULL,
	`notice_date` integer NOT NULL,
	`delivery_date` integer,
	`claimant_name` text NOT NULL,
	`carrier_name` text NOT NULL,
	`packages_damaged` integer DEFAULT 1 NOT NULL,
	`damaged_weight_kg` real NOT NULL,
	`claimed_amount` real NOT NULL,
	`claimed_currency` text DEFAULT 'EUR' NOT NULL,
	`statutory_sdr_rate` real NOT NULL,
	`statutory_limit_eur` real NOT NULL,
	`insurance_insured_value` real DEFAULT 0 NOT NULL,
	`insurance_policy_deductible` real DEFAULT 0 NOT NULL,
	`insurance_payout_amount` real DEFAULT 0 NOT NULL,
	`subrogation_recovered_amount` real DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'OPEN' NOT NULL,
	`protest_issued` integer DEFAULT false NOT NULL,
	`subrogation_signed` integer DEFAULT false NOT NULL,
	`incident_description` text NOT NULL,
	`surveyor_data` text,
	`recovery_notes` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `cargo_claims_claim_number_unique` ON `cargo_claims` (`claim_number`);