CREATE TABLE `road_consignments` (
	`id` text PRIMARY KEY NOT NULL,
	`consignment_number` text NOT NULL,
	`shipment_id` text,
	`consignment_type` text NOT NULL,
	`status` text DEFAULT 'PLANNED' NOT NULL,
	`sender_name` text NOT NULL,
	`sender_address` text NOT NULL,
	`sender_country` text NOT NULL,
	`consignee_name` text NOT NULL,
	`consignee_address` text NOT NULL,
	`consignee_country` text NOT NULL,
	`carrier_name` text NOT NULL,
	`carrier_vat` text NOT NULL,
	`tractor_plate` text NOT NULL,
	`trailer_plate` text NOT NULL,
	`driver_name` text NOT NULL,
	`driver_license` text NOT NULL,
	`driver_phone` text,
	`origin_city` text NOT NULL,
	`destination_city` text NOT NULL,
	`total_distance_km` real NOT NULL,
	`estimated_driving_hours` real NOT NULL,
	`required_rest_breaks_count` integer DEFAULT 0 NOT NULL,
	`pickup_date` integer NOT NULL,
	`delivery_date` integer,
	`total_pallets` integer DEFAULT 1 NOT NULL,
	`pallet_capacity_max` integer DEFAULT 33 NOT NULL,
	`total_gross_weight_kg` real NOT NULL,
	`payload_capacity_max_kg` real DEFAULT 24000 NOT NULL,
	`trailer_floor_utilization_pct` real NOT NULL,
	`is_adr_hazardous` integer DEFAULT false NOT NULL,
	`adr_total_points` real DEFAULT 0 NOT NULL,
	`adr_exemption_1136_applied` integer DEFAULT false NOT NULL,
	`orange_plates_required` integer DEFAULT false NOT NULL,
	`tunnel_restriction_code` text,
	`goods_description` text NOT NULL,
	`special_instructions` text,
	`cargo_items_data` text,
	`route_stops_data` text,
	`created_at` integer DEFAULT (strftime('%s', 'now')) NOT NULL,
	`updated_at` integer,
	`is_deleted` integer DEFAULT false NOT NULL,
	`is_active` integer DEFAULT true NOT NULL,
	`metadata` text,
	`tags` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `road_consignments_consignment_number_unique` ON `road_consignments` (`consignment_number`);