CREATE TABLE `charter_parties` (
	`id` text PRIMARY KEY NOT NULL,
	`fixture_reference` text NOT NULL,
	`charter_type` text DEFAULT 'VOYAGE_CHARTER' NOT NULL,
	`contract_form` text DEFAULT 'GENCON_2022' NOT NULL,
	`owner_name` text NOT NULL,
	`charterer_name` text NOT NULL,
	`broker_name` text,
	`vessel_name` text NOT NULL,
	`imo_number` text NOT NULL,
	`flag_state` text DEFAULT 'Malta' NOT NULL,
	`built_year` integer DEFAULT 2020,
	`summer_dwt_mt` real DEFAULT 45000,
	`gross_tonnage` real DEFAULT 28000,
	`cargo_description` text DEFAULT 'Trigo a Granel (Bulk Wheat)' NOT NULL,
	`cargo_quantity_mt` real DEFAULT 35000 NOT NULL,
	`quantity_margin_percentage` real DEFAULT 5 NOT NULL,
	`loading_port` text DEFAULT 'Puerto de Santander (ESSDR)' NOT NULL,
	`discharging_port` text DEFAULT 'Puerto de Alexandria (EGALY)' NOT NULL,
	`laycan_start` text NOT NULL,
	`laycan_end` text NOT NULL,
	`freight_rate_usd_per_mt` real DEFAULT 32.5,
	`daily_hire_rate_usd` real DEFAULT 18500,
	`demurrage_rate_usd_per_day` real DEFAULT 14000 NOT NULL,
	`despatch_rate_usd_per_day` real DEFAULT 7000 NOT NULL,
	`despatch_calculation_basis` text DEFAULT 'ATS_ALL_TIME_SAVED' NOT NULL,
	`laytime_terms` text DEFAULT 'SHEX_EIU' NOT NULL,
	`laytime_allowance_type` text DEFAULT 'LOADING_DISCHARGING_RATES' NOT NULL,
	`total_allowed_laytime_hours` real,
	`load_rate_mt_per_day` real DEFAULT 5000,
	`discharge_rate_mt_per_day` real DEFAULT 3500,
	`turn_time_hours` real DEFAULT 12 NOT NULL,
	`nor_office_hours_only` integer DEFAULT true NOT NULL,
	`nor_clauses_json` text DEFAULT '["WIPON","WIBON","WIFPON","WCCON"]' NOT NULL,
	`laytime_reversibility` text DEFAULT 'NON_REVERSIBLE' NOT NULL,
	`status` text DEFAULT 'FIXED_ACTIVE' NOT NULL,
	`remarks` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `charter_parties_fixture_reference_unique` ON `charter_parties` (`fixture_reference`);--> statement-breakpoint
CREATE TABLE `laytime_calculations` (
	`id` text PRIMARY KEY NOT NULL,
	`charter_party_id` text NOT NULL,
	`statement_of_facts_id` text NOT NULL,
	`calculation_reference` text NOT NULL,
	`port_operation` text DEFAULT 'LOADING' NOT NULL,
	`laytime_commenced_timestamp` text NOT NULL,
	`laytime_ceased_timestamp` text NOT NULL,
	`allowed_laytime_seconds` integer NOT NULL,
	`allowed_laytime_formatted` text NOT NULL,
	`gross_time_used_seconds` integer NOT NULL,
	`deductions_seconds` integer NOT NULL,
	`net_laytime_used_seconds` integer NOT NULL,
	`net_laytime_used_formatted` text NOT NULL,
	`time_difference_seconds` integer NOT NULL,
	`is_demurrage` integer NOT NULL,
	`demurrage_days_decimal` real DEFAULT 0 NOT NULL,
	`despatch_days_decimal` real DEFAULT 0 NOT NULL,
	`demurrage_rate_per_day_usd` real NOT NULL,
	`despatch_rate_per_day_usd` real NOT NULL,
	`total_demurrage_amount_usd` real DEFAULT 0 NOT NULL,
	`total_despatch_amount_usd` real DEFAULT 0 NOT NULL,
	`net_financial_payable_usd` real DEFAULT 0 NOT NULL,
	`calculation_method` text DEFAULT 'ATS_ALL_TIME_SAVED' NOT NULL,
	`settlement_status` text DEFAULT 'PENDING_AUDIT' NOT NULL,
	`auditor_notes` text,
	`calculated_at` text DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (`charter_party_id`) REFERENCES `charter_parties`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`statement_of_facts_id`) REFERENCES `statement_of_facts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `laytime_calculations_calculation_reference_unique` ON `laytime_calculations` (`calculation_reference`);--> statement-breakpoint
CREATE TABLE `sof_events` (
	`id` text PRIMARY KEY NOT NULL,
	`statement_of_facts_id` text NOT NULL,
	`event_start_timestamp` text NOT NULL,
	`event_end_timestamp` text NOT NULL,
	`duration_minutes` integer NOT NULL,
	`eventType` text DEFAULT 'WORKING_OPERATIONS' NOT NULL,
	`laytime_counting_percentage` real DEFAULT 100 NOT NULL,
	`is_counted_against_laytime` integer DEFAULT true NOT NULL,
	`affected_hatches_or_cranes` text DEFAULT 'Hold 1-4 / Shore Crane 2',
	`interruption_reason` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (`statement_of_facts_id`) REFERENCES `statement_of_facts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `statement_of_facts` (
	`id` text PRIMARY KEY NOT NULL,
	`charter_party_id` text NOT NULL,
	`sof_reference` text NOT NULL,
	`port_operation` text DEFAULT 'LOADING' NOT NULL,
	`port_code` text DEFAULT 'ESSDR' NOT NULL,
	`port_name` text DEFAULT 'Santander Port' NOT NULL,
	`terminal_berth` text DEFAULT 'Muelle de Raos 4',
	`vessel_agent_name` text DEFAULT 'Bergé Marítima',
	`master_name` text DEFAULT 'Capt. Santiago Aranda',
	`eosp_timestamp` text,
	`anchorage_drop_timestamp` text,
	`nor_tendered_timestamp` text NOT NULL,
	`nor_accepted_timestamp` text NOT NULL,
	`turn_time_expiry_timestamp` text,
	`all_fast_berthing_timestamp` text,
	`gangway_down_timestamp` text,
	`customs_health_cleared_timestamp` text,
	`draft_survey_start_timestamp` text,
	`draft_survey_end_timestamp` text,
	`commenced_operations_timestamp` text NOT NULL,
	`completed_operations_timestamp` text NOT NULL,
	`hoses_disconnected_timestamp` text,
	`vessel_sailed_timestamp` text,
	`actual_cargo_handled_mt` real DEFAULT 35000 NOT NULL,
	`is_finalized` integer DEFAULT false NOT NULL,
	`agent_notes` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP),
	`updated_at` text DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (`charter_party_id`) REFERENCES `charter_parties`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `statement_of_facts_sof_reference_unique` ON `statement_of_facts` (`sof_reference`);--> statement-breakpoint
CREATE TABLE `time_charter_off_hires` (
	`id` text PRIMARY KEY NOT NULL,
	`charter_party_id` text NOT NULL,
	`off_hire_reference` text NOT NULL,
	`off_hire_reason` text DEFAULT 'MAIN_ENGINE_BREAKDOWN' NOT NULL,
	`off_hire_start_timestamp` text NOT NULL,
	`off_hire_end_timestamp` text NOT NULL,
	`duration_hours` real NOT NULL,
	`duration_days_decimal` real NOT NULL,
	`daily_hire_rate_usd` real NOT NULL,
	`hire_deduction_usd` real NOT NULL,
	`bunker_vlsfo_consumed_mt` real DEFAULT 0,
	`bunker_mgo_consumed_mt` real DEFAULT 0,
	`vlsfo_price_usd_per_mt` real DEFAULT 580,
	`mgo_price_usd_per_mt` real DEFAULT 750,
	`bunker_compensation_usd` real DEFAULT 0 NOT NULL,
	`total_off_hire_claim_usd` real NOT NULL,
	`off_hire_status` text DEFAULT 'LOGGED' NOT NULL,
	`incident_description` text,
	`created_at` text DEFAULT (CURRENT_TIMESTAMP),
	FOREIGN KEY (`charter_party_id`) REFERENCES `charter_parties`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `time_charter_off_hires_off_hire_reference_unique` ON `time_charter_off_hires` (`off_hire_reference`);