CREATE TABLE `ga_adjustments` (
	`id` text PRIMARY KEY NOT NULL,
	`ga_case_id` text NOT NULL,
	`adjustment_reference` text NOT NULL,
	`adjustment_date` text NOT NULL,
	`total_allowances_usd` real NOT NULL,
	`total_ship_allowances_usd` real DEFAULT 0 NOT NULL,
	`total_cargo_allowances_usd` real DEFAULT 0 NOT NULL,
	`total_refuge_expenses_usd` real DEFAULT 0 NOT NULL,
	`total_salvage_award_usd` real DEFAULT 0 NOT NULL,
	`total_commission_usd` real DEFAULT 0 NOT NULL,
	`cmi_interest_rate_percentage` real DEFAULT 6 NOT NULL,
	`total_cmi_interest_usd` real DEFAULT 0 NOT NULL,
	`total_contributory_value_usd` real NOT NULL,
	`vessel_contributory_value_usd` real DEFAULT 0 NOT NULL,
	`freight_contributory_value_usd` real DEFAULT 0 NOT NULL,
	`cargo_contributory_value_usd` real DEFAULT 0 NOT NULL,
	`containers_contributory_value_usd` real DEFAULT 0 NOT NULL,
	`final_rate_of_contribution_percentage` real NOT NULL,
	`total_debtor_contributions_usd` real DEFAULT 0 NOT NULL,
	`total_creditor_recoveries_usd` real DEFAULT 0 NOT NULL,
	`adjuster_certification_statement` text NOT NULL,
	`status` text DEFAULT 'DRAFT' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`ga_case_id`) REFERENCES `ga_cases`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ga_adjustments_adjustment_reference_unique` ON `ga_adjustments` (`adjustment_reference`);--> statement-breakpoint
CREATE TABLE `ga_allowances` (
	`id` text PRIMARY KEY NOT NULL,
	`ga_case_id` text NOT NULL,
	`allowance_category` text NOT NULL,
	`yar_rule_reference` text NOT NULL,
	`description` text NOT NULL,
	`credited_party_type` text NOT NULL,
	`credited_party_name` text NOT NULL,
	`original_currency_amount` real NOT NULL,
	`original_currency` text DEFAULT 'USD' NOT NULL,
	`exchange_rate_to_usd` real DEFAULT 1 NOT NULL,
	`amount_usd` real NOT NULL,
	`is_admissible` integer DEFAULT true NOT NULL,
	`remarks` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`ga_case_id`) REFERENCES `ga_cases`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `ga_cases` (
	`id` text PRIMARY KEY NOT NULL,
	`case_reference` text NOT NULL,
	`vessel_name` text NOT NULL,
	`imo_number` text NOT NULL,
	`flag_state` text NOT NULL,
	`built_year` integer NOT NULL,
	`gross_tonnage` integer NOT NULL,
	`summer_dwt_mt` real NOT NULL,
	`shipowner_name` text NOT NULL,
	`disponent_owner_or_charterer` text,
	`master_name` text NOT NULL,
	`casualty_type` text NOT NULL,
	`casualty_date` text NOT NULL,
	`casualty_location` text NOT NULL,
	`voyage_origin` text NOT NULL,
	`voyage_destination` text NOT NULL,
	`port_of_refuge` text NOT NULL,
	`date_arrival_port_of_refuge` text,
	`date_departure_port_of_refuge` text,
	`governing_rules` text DEFAULT 'YAR_2016' NOT NULL,
	`salvage_contract_type` text DEFAULT 'LOF_2024_SCOPIC' NOT NULL,
	`salvor_name` text,
	`average_adjuster_firm` text NOT NULL,
	`lead_adjuster_name` text NOT NULL,
	`estimated_loss_usd` real DEFAULT 0 NOT NULL,
	`estimated_contribution_percentage` real DEFAULT 7.5 NOT NULL,
	`declaration_narrative` text NOT NULL,
	`currency_code` text DEFAULT 'USD' NOT NULL,
	`status` text DEFAULT 'DECLARED_ACTIVE' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ga_cases_case_reference_unique` ON `ga_cases` (`case_reference`);--> statement-breakpoint
CREATE TABLE `ga_contributory_interests` (
	`id` text PRIMARY KEY NOT NULL,
	`ga_case_id` text NOT NULL,
	`interest_category` text NOT NULL,
	`bl_reference` text,
	`container_number` text,
	`owner_or_receiver_name` text NOT NULL,
	`cargo_description` text,
	`weight_or_teu` real,
	`sound_value_destination_usd` real NOT NULL,
	`particular_damage_deduction_usd` real DEFAULT 0 NOT NULL,
	`made_good_allowance_usd` real DEFAULT 0 NOT NULL,
	`contributory_value_usd` real NOT NULL,
	`calculated_contribution_usd` real DEFAULT 0 NOT NULL,
	`net_financial_balance_usd` real DEFAULT 0 NOT NULL,
	`balance_type` text DEFAULT 'PAYABLE_DEBTOR' NOT NULL,
	`has_security_provided` integer DEFAULT false NOT NULL,
	`cargo_release_authorized` integer DEFAULT false NOT NULL,
	`created_at` text NOT NULL,
	FOREIGN KEY (`ga_case_id`) REFERENCES `ga_cases`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `ga_securities` (
	`id` text PRIMARY KEY NOT NULL,
	`ga_case_id` text NOT NULL,
	`contributory_interest_id` text NOT NULL,
	`security_reference` text NOT NULL,
	`security_type` text DEFAULT 'AVERAGE_BOND_AND_GUARANTEE' NOT NULL,
	`cargo_consignee_name` text NOT NULL,
	`cargo_consignee_vat` text,
	`insurer_name` text,
	`insurer_policy_number` text,
	`insurer_contact_email` text,
	`security_amount_usd` real NOT NULL,
	`deposit_bank_name` text,
	`deposit_bank_account_number` text,
	`cash_deposit_receipt_number` text,
	`average_bond_signed` integer DEFAULT false NOT NULL,
	`average_bond_sign_date` text,
	`average_guarantee_signed` integer DEFAULT false NOT NULL,
	`average_guarantee_sign_date` text,
	`cargo_release_authorized` integer DEFAULT false NOT NULL,
	`release_authorized_by` text,
	`release_timestamp` text,
	`status` text DEFAULT 'SECURITY_PENDING' NOT NULL,
	`remarks` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`ga_case_id`) REFERENCES `ga_cases`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`contributory_interest_id`) REFERENCES `ga_contributory_interests`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `ga_securities_security_reference_unique` ON `ga_securities` (`security_reference`);