mutation UpsertUser($uid: String!, $email: String!, $role: String!)
@auth(level: USER) {
  user_upsert(data: { uid: $uid, email: $email, role: $role })
}

query GetUserRole($uid: String!) @auth(level: USER) {
  users(where: { uid: { eq: $uid } }) {
    role
    email
  }
}

query GetAllUsers @auth(level: USER) {
  users {
    uid
    email
    role
  }
}

mutation UpdateUserRole($uid: String!, $role: String!) @auth(level: USER) {
  user_update(key: { uid: $uid }, data: { role: $role })
}
