import { executeQuery, executeMutation, DataConnect } from 'firebase/data-connect';

// These queries match the Operations generated by Firebase Gemini
const LIST_SHIPMENTS_QUERY = `
  query ListShipments {
    shipments {
      id
      trackingNumber
      origin
      destination
      status
    }
  }
`;

const CREATE_SHIPMENT_MUTATION = `
  mutation CreateShipment($trackingNumber: String!, $origin: String!, $destination: String!) {
    shipment_insert(data: {
      trackingNumber: $trackingNumber,
      origin: $origin,
      destination: $destination,
      status: "PENDING"
    })
  }
`;

export class SCMDataConnectService {
  constructor(private dc: DataConnect) {}

  async listShipments() {
    try {
      const response = await executeQuery<any, any>(this.dc, LIST_SHIPMENTS_QUERY);
      return response.data.shipments;
    } catch (e) {
      console.error("Data Connect Error:", e);
      return [];
    }
  }

  async createShipment(trackingNumber: string, origin: string, destination: string) {
    try {
      await executeMutation<any, any>(this.dc, CREATE_SHIPMENT_MUTATION, {
        trackingNumber, origin, destination
      });
    } catch (e) {
      console.error("Data Connect Error:", e);
    }
  }
}
