extend type Company {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Company", purpose: IMPLICIT_KEY_FIELD)
}
extend type Document {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Document", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Document`.`shipment`. It must match the value of `Shipment`.`id`. See `@ref` for how to customize it.
  """
  shipmentId: UUID! @fdc_generated(from: "Document.shipment", purpose: IMPLICIT_REF_FIELD)
}
extend type Milestone {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Milestone", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Milestone`.`shipment`. It must match the value of `Shipment`.`id`. See `@ref` for how to customize it.
  """
  shipmentId: UUID! @fdc_generated(from: "Milestone.shipment", purpose: IMPLICIT_REF_FIELD)
}
extend type Quote {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Quote", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Quote`.`carrier`. It must match the value of `Company`.`id`. See `@ref` for how to customize it.
  """
  carrierId: UUID! @fdc_generated(from: "Quote.carrier", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Quote`.`createdBy`. It must match the value of `User`.`uid`. See `@ref` for how to customize it.
  """
  createdByUid: String! @fdc_generated(from: "Quote.createdBy", purpose: IMPLICIT_REF_FIELD)
}
extend type Shipment {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Shipment", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Shipment`.`consignee`. It must match the value of `Company`.`id`. See `@ref` for how to customize it.
  """
  consigneeId: UUID! @fdc_generated(from: "Shipment.consignee", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Shipment`.`relatedQuote`. It must match the value of `Quote`.`id`. See `@ref` for how to customize it.
  """
  relatedQuoteId: UUID @fdc_generated(from: "Shipment.relatedQuote", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Shipment`.`shipper`. It must match the value of `Company`.`id`. See `@ref` for how to customize it.
  """
  shipperId: UUID! @fdc_generated(from: "Shipment.shipper", purpose: IMPLICIT_REF_FIELD)
}
extend type Workflow {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Workflow", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Workflow`.`shipment`. It must match the value of `Shipment`.`id`. See `@ref` for how to customize it.
  """
  shipmentId: UUID! @fdc_generated(from: "Workflow.shipment", purpose: IMPLICIT_REF_FIELD)
}
