import { db } from "../index.js";
import * as schema from "../schema/index.js";
import { faker } from "@faker-js/faker";
import { sql } from "drizzle-orm";

export async function seedCustomsWarehouse(): Promise<void> {
  // 17. CUSTOMS WAREHOUSE, FREE ZONE & SPECIAL REGIMES
  await db
    .insert(schema.customsFacilities)
    .values([
      {
        id: "fac_da_bcn_zal",
        facilityCode: "ES-DA-08001-ZAL",
        name: "Depósito Aduanero ZAL Port Barcelona",
        facilityType: "CUSTOMS_WAREHOUSE_DA",
        customsAuthorityAuthorizationRef: "ES-AET-2024-DA-4910",
        managingOperatorName: "Atlas Logistics Port Services S.A.",
        locationAddress: "Av. Ports d'Europa 100, Sector ZAL Prat",
        city: "Barcelona",
        countryCode: "ES",
        totalPalletCapacity: 15000,
        occupiedPallets: 8420,
        totalVolumeM3: 35000.0,
        maxStayDaysLimit: null, // Ilimitado en DA
        isReeferCertified: true,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "fac_dda_mad_cos",
        facilityCode: "ES-DDA-28002-COS",
        name: "Depósito Distinto del Aduanero Coslada Hub",
        facilityType: "NON_CUSTOMS_WAREHOUSE_DDA",
        customsAuthorityAuthorizationRef: "ES-AET-2023-DDA-1822",
        managingOperatorName: "Atlas Logistics Central Hub S.L.",
        locationAddress: "Centro de Carga Aérea & Intermodal Coslada, Nave 4",
        city: "Madrid",
        countryCode: "ES",
        totalPalletCapacity: 12000,
        occupiedPallets: 5100,
        totalVolumeM3: 28000.0,
        maxStayDaysLimit: null,
        isReeferCertified: false,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "fac_adt_vlc_port",
        facilityCode: "ES-ADT-46003-VLC",
        name: "Almacén de Depósito Temporal Valencia Muelle Sur",
        facilityType: "TEMPORARY_STORAGE_ADT",
        customsAuthorityAuthorizationRef: "ES-AET-2025-ADT-7701",
        managingOperatorName: "Atlas Intermodal Valencia S.L.",
        locationAddress: "Muelle de la Xitxarra s/n, Recinto Portuario",
        city: "Valencia",
        countryCode: "ES",
        totalPalletCapacity: 8500,
        occupiedPallets: 3200,
        totalVolumeM3: 20000.0,
        maxStayDaysLimit: 90, // Límite legal 90 días Art. 149 CAU
        isReeferCertified: true,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "fac_zf_cadiz",
        facilityCode: "ES-ZF-11004-CAD",
        name: "Consorcio Zona Franca de Cádiz - Recinto Fiscal",
        facilityType: "FREE_ZONE_ZF",
        customsAuthorityAuthorizationRef: "ES-AET-2022-ZF-0012",
        managingOperatorName: "Consorcio de la Zona Franca de Cádiz",
        locationAddress: "Calle Ronda de Vigilancia s/n",
        city: "Cádiz",
        countryCode: "ES",
        totalPalletCapacity: 25000,
        occupiedPallets: 14200,
        totalVolumeM3: 60000.0,
        maxStayDaysLimit: null,
        isReeferCertified: true,
        isActive: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ])
    .onConflictDoNothing();

  await db
    .insert(schema.customsGuarantees)
    .values([
      {
        id: "guar_santander_bcn",
        guaranteeReferenceNumber: "GRN-2026-AEAT-00918",
        customsOfficeCode: "ES000801",
        guarantorFinancialInstitution: "Banco Santander S.A.",
        totalGuaranteeAmountEur: 1500000.0,
        committedSuspendedDebtEur: 127635.0, // 73500 + 54135
        availableCreditEur: 1372365.0,
        validFromDate: "2026-01-01T00:00:00Z",
        expiryDate: "2026-12-31T23:59:59Z",
        status: "ACTIVE",
        remarks:
          "Aval global bancario permanente para operaciones de Depósito Aduanero ante la Dependencia Regional de Aduanas e IIEE de Cataluña.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "guar_bbva_mad",
        guaranteeReferenceNumber: "GRN-2026-AEAT-00445",
        customsOfficeCode: "ES002801",
        guarantorFinancialInstitution: "Banco Bilbao Vizcaya Argentaria (BBVA)",
        totalGuaranteeAmountEur: 800000.0,
        committedSuspendedDebtEur: 89080.8, // 55336.8 + 33744
        availableCreditEur: 710919.2,
        validFromDate: "2026-01-01T00:00:00Z",
        expiryDate: "2026-12-31T23:59:59Z",
        status: "ACTIVE",
        remarks:
          "Garantía global aduanera para Almacén de Depósito Temporal y DDA en Madrid Barajas / Coslada.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ])
    .onConflictDoNothing();

  await db
    .insert(schema.customsInventoryLots)
    .values([
      {
        id: "lot_elec_semi_01",
        lotNumber: "LOT-2026-DA-08101",
        facilityId: "fac_da_bcn_zal",
        guaranteeId: "guar_santander_bcn",
        inclusionDvdNumber: "DVD-2026-7100-00412",
        inclusionDuaMrn: "26ES00080100412891",
        customsRegimeCode: "7100",
        ownerCompanyName: "IberMicro Electronics S.L.",
        ownerTaxIdEori: "ESB88491029",
        taricCommodityCode: "8542319000",
        goodsDescription:
          "Microprocesadores y circuitos integrados monolíticos para automoción",
        originCountryCode: "TW",
        initialPackageCount: 120,
        currentPackageCount: 100, // 20 descargados
        initialGrossMassKg: 2400.0,
        currentGrossMassKg: 2000.0,
        initialNetMassKg: 2100.0,
        currentNetMassKg: 1750.0,
        customsValueEur: 350000.0,
        dutyTariffRatePercent: 0.0,
        importVatRatePercent: 21.0,
        suspendedDutyAmountEur: 0.0,
        suspendedVatAmountEur: 73500.0,
        totalSuspendedDebtEur: 73500.0,
        inclusionDate: "2026-07-15T10:30:00Z",
        maxStayDeadlineDate: null,
        status: "PARTIALLY_DISCHARGED",
        warehouseLocationRack: "RACK-E-14-02",
        responsibleCustomsAgent: "Carles Puigvert (Agente Colegiado 881)",
        remarks:
          "Mercancía tecnológica de alto valor en custodia aduanera con control de humedad.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "lot_alum_coils_02",
        lotNumber: "LOT-2026-DA-08102",
        facilityId: "fac_da_bcn_zal",
        guaranteeId: "guar_santander_bcn",
        inclusionDvdNumber: "DVD-2026-7100-00413",
        inclusionDuaMrn: "26ES00080100412892",
        customsRegimeCode: "7100",
        ownerCompanyName: "Aluminios Ibéricos Industriales S.A.",
        ownerTaxIdEori: "ESA28941038",
        taricCommodityCode: "7606129200",
        goodsDescription:
          "Chapas y bandas laminadas de aleación de aluminio de espesor > 0,2 mm",
        originCountryCode: "IN",
        initialPackageCount: 24,
        currentPackageCount: 18, // 6 reexportadas
        initialGrossMassKg: 48000.0,
        currentGrossMassKg: 36000.0,
        initialNetMassKg: 47500.0,
        currentNetMassKg: 35625.0,
        customsValueEur: 180000.0,
        dutyTariffRatePercent: 7.5,
        importVatRatePercent: 21.0,
        suspendedDutyAmountEur: 13500.0,
        suspendedVatAmountEur: 40635.0,
        totalSuspendedDebtEur: 54135.0,
        inclusionDate: "2026-08-01T08:00:00Z",
        maxStayDeadlineDate: null,
        status: "PARTIALLY_DISCHARGED",
        warehouseLocationRack: "ZONA-PESADA-P04",
        responsibleCustomsAgent: "Carles Puigvert (Agente Colegiado 881)",
        remarks: "Bobinas con certificado CBAM verificado por instalación.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "lot_mach_robot_03",
        lotNumber: "LOT-2026-ADT-46101",
        facilityId: "fac_adt_vlc_port",
        guaranteeId: "guar_bbva_mad",
        inclusionDvdNumber: "ADT-2026-VLC-00891",
        inclusionDuaMrn: "26ES00460100781290",
        customsRegimeCode: "ADT_STAY",
        ownerCompanyName: "Robótica Avanzada del Mediterráneo S.L.",
        ownerTaxIdEori: "ESB96102834",
        taricCommodityCode: "8479899790",
        goodsDescription:
          "Brazos robóticos multieje para líneas de montaje automatizado",
        originCountryCode: "JP",
        initialPackageCount: 8,
        currentPackageCount: 8,
        initialGrossMassKg: 16000.0,
        currentGrossMassKg: 16000.0,
        initialNetMassKg: 15200.0,
        currentNetMassKg: 15200.0,
        customsValueEur: 240000.0,
        dutyTariffRatePercent: 1.7,
        importVatRatePercent: 21.0,
        suspendedDutyAmountEur: 4080.0,
        suspendedVatAmountEur: 51256.8,
        totalSuspendedDebtEur: 55336.8,
        inclusionDate: "2026-08-10T14:20:00Z",
        maxStayDeadlineDate: "2026-11-08T23:59:59Z", // 90 días
        status: "ACTIVE",
        warehouseLocationRack: "ADT-BAY-02",
        responsibleCustomsAgent: "Vicente Blasco (Agente Colegiado 412)",
        remarks:
          "En espera de decisión de destino aduanero definitivo antes de 90 días.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "lot_textile_garments_04",
        lotNumber: "LOT-2026-DDA-28101",
        facilityId: "fac_dda_mad_cos",
        guaranteeId: "guar_bbva_mad",
        inclusionDvdNumber: "DVD-2026-7600-00105",
        inclusionDuaMrn: "26ES00280100105821",
        customsRegimeCode: "7600",
        ownerCompanyName: "Moda & Logística Internacional S.A.",
        ownerTaxIdEori: "ESA28019284",
        taricCommodityCode: "6109100010",
        goodsDescription:
          "Camisetas de punto de algodón orgánico para distribución comunitaria",
        originCountryCode: "TR",
        initialPackageCount: 500,
        currentPackageCount: 500,
        initialGrossMassKg: 7500.0,
        currentGrossMassKg: 7500.0,
        initialNetMassKg: 7100.0,
        currentNetMassKg: 7100.0,
        customsValueEur: 95000.0,
        dutyTariffRatePercent: 12.0,
        importVatRatePercent: 21.0,
        suspendedDutyAmountEur: 11400.0,
        suspendedVatAmountEur: 22344.0,
        totalSuspendedDebtEur: 33744.0,
        inclusionDate: "2026-08-18T11:00:00Z",
        maxStayDeadlineDate: null,
        status: "ACTIVE",
        warehouseLocationRack: "TEXTIL-RACK-08",
        responsibleCustomsAgent: "Elena Morales (Agente Colegiado 620)",
        remarks:
          "Régimen DDA con exención de IVA en entregas sucesivas intracomunitarias.",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ])
    .onConflictDoNothing();

  await db
    .insert(schema.customsStockLedgerEntries)
    .values([
      {
        id: "led_entry_001",
        entrySequentialNumber: 1001,
        lotId: "lot_elec_semi_01",
        facilityId: "fac_da_bcn_zal",
        movementType: "INCLUSION_BONDING",
        documentReference: "DVD-2026-7100-00412 (DUA 26ES00080100412891)",
        packagesDelta: 120,
        packagesBalanceAfter: 120,
        grossMassDeltaKg: 2400.0,
        grossMassBalanceAfterKg: 2400.0,
        releasedSuspendedDebtEur: 0.0,
        movementTimestamp: "2026-07-15T10:35:00Z",
        authorizedOfficerOrAgent: "Carles Puigvert",
        notes:
          "Inclusión y vinculación reglamentaria en Depósito Aduanero público bajo régimen 7100.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "led_entry_002",
        entrySequentialNumber: 1002,
        lotId: "lot_elec_semi_01",
        facilityId: "fac_da_bcn_zal",
        movementType: "USUAL_HANDLING_ART220",
        documentReference: "AUT-MANIP-2026-08101",
        packagesDelta: 0,
        packagesBalanceAfter: 120,
        grossMassDeltaKg: 0.0,
        grossMassBalanceAfterKg: 2400.0,
        releasedSuspendedDebtEur: 0.0,
        movementTimestamp: "2026-07-22T09:15:00Z",
        authorizedOfficerOrAgent: "Carles Puigvert",
        notes:
          "Manipulación usual autorizada Art. 220 CAU: Etiquetado de trazabilidad CE y sobreembalaje protector.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "led_entry_003",
        entrySequentialNumber: 1003,
        lotId: "lot_elec_semi_01",
        facilityId: "fac_da_bcn_zal",
        movementType: "PARTIAL_DISCHARGE",
        documentReference: "DVD-OUT-2026-00301 (DUA 26ES00080100910011)",
        packagesDelta: -20,
        packagesBalanceAfter: 100,
        grossMassDeltaKg: -400.0,
        grossMassBalanceAfterKg: 2000.0,
        releasedSuspendedDebtEur: 12250.0, // (20/120) * 73500
        movementTimestamp: "2026-08-12T16:00:00Z",
        authorizedOfficerOrAgent: "Carles Puigvert",
        notes:
          "Desvinculación parcial para Despacho a Libre Práctica (Régimen 4071) con pago de IVA.",
        createdAt: new Date().toISOString(),
      },
      {
        id: "led_entry_004",
        entrySequentialNumber: 1004,
        lotId: "lot_alum_coils_02",
        facilityId: "fac_da_bcn_zal",
        movementType: "INCLUSION_BONDING",
        documentReference: "DVD-2026-7100-00413 (DUA 26ES00080100412892)",
        packagesDelta: 24,
        packagesBalanceAfter: 24,
        grossMassDeltaKg: 48000.0,
        grossMassBalanceAfterKg: 48000.0,
        releasedSuspendedDebtEur: 0.0,
        movementTimestamp: "2026-08-01T08:10:00Z",
        authorizedOfficerOrAgent: "Carles Puigvert",
        notes:
          "Inclusión de bobinas de aluminio bajo régimen 7100 con aval Santander.",
        createdAt: new Date().toISOString(),
      },
    ])
    .onConflictDoNothing();

  await db
    .insert(schema.customsDischargeDeclarations)
    .values([
      {
        id: "dvd_out_2026_01",
        dischargeDeclarationNumber: "DVD-OUT-2026-00301",
        lotId: "lot_elec_semi_01",
        dischargeRegimeCode: "4071",
        dischargeDuaMrn: "26ES00080100910011",
        dischargedPackagesCount: 20,
        dischargedGrossMassKg: 400.0,
        dischargedCustomsValueEur: 58333.33,
        settledDutyAmountEur: 0.0,
        settledVatAmountEur: 12250.0,
        totalSettledTaxesEur: 12250.0,
        releasedGuaranteeCreditEur: 12250.0,
        destinationConsigneeName: "Automotive Chips Europa S.A.",
        destinationCountryCode: "ES",
        dischargeDate: "2026-08-12T16:00:00Z",
        status: "AUTHORIZED_RELEASE",
        customsClearanceOfficer: "Elena Morales (Inspectora de Aduanas)",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "dvd_out_2026_02",
        dischargeDeclarationNumber: "DVD-OUT-2026-00302",
        lotId: "lot_alum_coils_02",
        dischargeRegimeCode: "3171",
        dischargeDuaMrn: "26ES00080100910012",
        dischargedPackagesCount: 6,
        dischargedGrossMassKg: 12000.0,
        dischargedCustomsValueEur: 45000.0,
        settledDutyAmountEur: 0.0,
        settledVatAmountEur: 0.0,
        totalSettledTaxesEur: 0.0, // Exención por reexportación a tercer país
        releasedGuaranteeCreditEur: 13533.75, // (6/24) * 54135
        destinationConsigneeName: "Maghreb Aluminium Extrusion SARL",
        destinationCountryCode: "MA",
        dischargeDate: "2026-08-20T11:30:00Z",
        status: "AUTHORIZED_RELEASE",
        customsClearanceOfficer: "Elena Morales (Inspectora de Aduanas)",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ])
    .onConflictDoNothing();

  console.log(
    "✅ Creadas Instalaciones Aduaneras (DA/DDA/ADT/ZF), Avales Globales, Lotes y Libro de Existencias.",
  );
}
