import { db } from "../index.js";
import * as schema from "../schema/index.js";
import { faker } from "@faker-js/faker";
import { sql } from "drizzle-orm";

export async function seedTreasury(): Promise<void> {
  // ==========================================
  // 13. TESORERÍA MULTIDIVISA & FACTURAS DE PORTEADORES (3-WAY MATCH & CASS)
  // ==========================================
  console.log(
    "⚙️ Inyectando Tipos de Cambio FX, Posiciones de Tesorería y Facturas CASS / Navieras...",
  );

  // Seed FX Rates
  await db
    .insert(schema.fxRates)
    .values([
      {
        id: "fx_eur_usd",
        fromCurrency: "EUR",
        toCurrency: "USD",
        spotRate: 1.085,
        effectiveDate: "2026-08-27",
        source: "ECB",
        forward30Rate: 1.0865,
        forward60Rate: 1.088,
        forward90Rate: 1.0895,
      },
      {
        id: "fx_eur_gbp",
        fromCurrency: "EUR",
        toCurrency: "GBP",
        spotRate: 0.855,
        effectiveDate: "2026-08-27",
        source: "ECB",
        forward30Rate: 0.856,
        forward60Rate: 0.857,
        forward90Rate: 0.858,
      },
      {
        id: "fx_eur_cny",
        fromCurrency: "EUR",
        toCurrency: "CNY",
        spotRate: 7.82,
        effectiveDate: "2026-08-27",
        source: "PBOC",
        forward30Rate: 7.835,
        forward60Rate: 7.85,
        forward90Rate: 7.865,
      },
      {
        id: "fx_eur_jpy",
        fromCurrency: "EUR",
        toCurrency: "JPY",
        spotRate: 162.4,
        effectiveDate: "2026-08-27",
        source: "BoJ",
        forward30Rate: 162.8,
        forward60Rate: 163.2,
        forward90Rate: 163.6,
      },
      {
        id: "fx_eur_chf",
        fromCurrency: "EUR",
        toCurrency: "CHF",
        spotRate: 0.955,
        effectiveDate: "2026-08-27",
        source: "SNB",
        forward30Rate: 0.956,
        forward60Rate: 0.957,
        forward90Rate: 0.958,
      },
    ])
    .onConflictDoNothing();

  // Seed Treasury FX Positions
  await db
    .insert(schema.treasuryFxPositions)
    .values([
      {
        id: "pos_usd",
        currency: "USD",
        receivablesAmount: 185000.0,
        payablesAmount: 142000.0,
        netExposure: 43000.0,
        averageExchangeRate: 1.078,
        currentSpotRate: 1.085,
        unrealizedGainLossEur: 1180.5,
        hedgedAmount: 25000.0,
        unhedgedAmount: 18000.0,
        riskLevel: "LOW",
      },
      {
        id: "pos_gbp",
        currency: "GBP",
        receivablesAmount: 32000.0,
        payablesAmount: 48500.0,
        netExposure: -16500.0,
        averageExchangeRate: 0.852,
        currentSpotRate: 0.855,
        unrealizedGainLossEur: -340.2,
        hedgedAmount: 10000.0,
        unhedgedAmount: 6500.0,
        riskLevel: "MODERATE",
      },
      {
        id: "pos_cny",
        currency: "CNY",
        receivablesAmount: 0.0,
        payablesAmount: 350000.0,
        netExposure: -350000.0,
        averageExchangeRate: 7.8,
        currentSpotRate: 7.82,
        unrealizedGainLossEur: -520.0,
        hedgedAmount: 200000.0,
        unhedgedAmount: 150000.0,
        riskLevel: "HIGH",
      },
    ])
    .onConflictDoNothing();

  // Seed Carrier Invoices (Maersk Ocean, Iberia CASS, Trans-Iberian Road)
  await db
    .insert(schema.carrierInvoices)
    .values([
      {
        id: "inv_maersk_88910",
        invoiceNumber: "MSK-INV-2026-88910",
        carrierName: "Maersk Line A/S",
        carrierVat: "DK-13579246",
        mode: "OCEAN_FCL",
        invoiceDate: "2026-08-15",
        dueDate: "2026-09-14",
        billingPeriod: "2026-08",
        currency: "USD",
        totalAmount: 5450.0,
        matchedAmount: 4200.0,
        disputedAmount: 1250.0,
        reconciliationStatus: "DISCREPANCY_FLAGGED",
        paymentTerms: "30_DAYS",
        notes:
          "Sobrecargo de demurrage de 5 días en terminal de Valencia en disputa por huelga portuaria.",
      },
      {
        id: "inv_cass_ib_0826",
        invoiceNumber: "CASS-ES-2026-08-IB01",
        carrierName: "Iberia Líneas Aéreas de España (IATA CASS)",
        carrierVat: "ESA28014523",
        mode: "AIR_CARGO",
        invoiceDate: "2026-08-20",
        dueDate: "2026-09-05",
        billingPeriod: "2026-08-W3",
        currency: "EUR",
        totalAmount: 4120.0,
        matchedAmount: 4120.0,
        disputedAmount: 0.0,
        reconciliationStatus: "AUTO_MATCHED",
        cassStatementNumber: "CASS-IB-99201",
        paymentTerms: "15_DAYS",
        notes:
          "Liquidación quincenal CASS España. Todas las cartas de porte aéreo coinciden al 100%.",
      },
      {
        id: "inv_tie_4412",
        invoiceNumber: "TIE-INV-2026-4412",
        carrierName: "Trans-Iberian Express S.L.",
        carrierVat: "ESB88442211",
        mode: "ROAD_FREIGHT",
        invoiceDate: "2026-08-22",
        dueDate: "2026-09-21",
        billingPeriod: "2026-08",
        currency: "EUR",
        totalAmount: 1850.0,
        matchedAmount: 1850.0,
        disputedAmount: 0.0,
        reconciliationStatus: "APPROVED_FOR_PAYMENT",
        paymentTerms: "30_DAYS",
        notes:
          "Transporte FTL Madrid -> Lyon completado según e-CMR CMR-2026-99210.",
      },
    ])
    .onConflictDoNothing();

  // Seed Carrier Invoice Lines
  await db
    .insert(schema.carrierInvoiceLines)
    .values([
      // Maersk Invoice Lines
      {
        id: "line_msk_01",
        carrierInvoiceId: "inv_maersk_88910",
        bookingNumber: "BKG-2026-0849",
        documentNumber: "MSK99482015",
        chargeCode: "BASIC_FREIGHT",
        description: "Flete Marítimo FCL 1x40HC Shanghai -> Valencia",
        billedQuantity: 1,
        billedRate: 3200.0,
        billedAmount: 3200.0,
        expectedQuantity: 1,
        expectedRate: 3200.0,
        expectedAmount: 3200.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_msk_02",
        carrierInvoiceId: "inv_maersk_88910",
        bookingNumber: "BKG-2026-0849",
        documentNumber: "MSK99482015",
        chargeCode: "BAF_FUEL",
        description: "Bunker Adjustment Factor (BAF)",
        billedQuantity: 1,
        billedRate: 650.0,
        billedAmount: 650.0,
        expectedQuantity: 1,
        expectedRate: 650.0,
        expectedAmount: 650.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_msk_03",
        carrierInvoiceId: "inv_maersk_88910",
        bookingNumber: "BKG-2026-0849",
        documentNumber: "MSK99482015",
        chargeCode: "THC_ORIGIN",
        description: "Terminal Handling Charge Shanghai",
        billedQuantity: 1,
        billedRate: 350.0,
        billedAmount: 350.0,
        expectedQuantity: 1,
        expectedRate: 350.0,
        expectedAmount: 350.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_msk_04",
        carrierInvoiceId: "inv_maersk_88910",
        bookingNumber: "BKG-2026-0849",
        documentNumber: "MSK99482015",
        chargeCode: "DEMURRAGE",
        description: "Demurrage & Detention Puerto de Valencia (5 días extra)",
        billedQuantity: 5,
        billedRate: 250.0,
        billedAmount: 1250.0,
        expectedQuantity: 3,
        expectedRate: 250.0,
        expectedAmount: 750.0,
        varianceAmount: 500.0,
        variancePercentage: 66.67,
        isWithinTolerance: false,
        disputeReason:
          "Discrepancia en demoras: 2 de los 5 días facturados corresponden al cierre de terminal por huelga de estiba (fuerza mayor). Solicitada anulación de 500 USD.",
        disputeStatus: "DISPUTED",
      },
      // CASS Invoice Lines
      {
        id: "line_cass_01",
        carrierInvoiceId: "inv_cass_ib_0826",
        bookingNumber: "AIR-BKG-84920",
        documentNumber: "075-84920153",
        chargeCode: "BASIC_FREIGHT",
        description: "Flete Aéreo MAD -> JFK (480 kg chargeable)",
        billedQuantity: 480,
        billedRate: 4.5,
        billedAmount: 2160.0,
        expectedQuantity: 480,
        expectedRate: 4.5,
        expectedAmount: 2160.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_cass_02",
        carrierInvoiceId: "inv_cass_ib_0826",
        bookingNumber: "AIR-BKG-84920",
        documentNumber: "075-84920153",
        chargeCode: "SECURITY_FEE",
        description: "Recargo de Seguridad y Combustible Aéreo",
        billedQuantity: 480,
        billedRate: 1.0,
        billedAmount: 480.0,
        expectedQuantity: 480,
        expectedRate: 1.0,
        expectedAmount: 480.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_cass_03",
        carrierInvoiceId: "inv_cass_ib_0826",
        bookingNumber: "AIR-BKG-84920",
        documentNumber: "075-84920153",
        chargeCode: "IATA_COMMISSION",
        description: "Comisión Transitario IATA CASS (5%)",
        billedQuantity: 1,
        billedRate: -108.0,
        billedAmount: -108.0,
        expectedQuantity: 1,
        expectedRate: -108.0,
        expectedAmount: -108.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      {
        id: "line_cass_04",
        carrierInvoiceId: "inv_cass_ib_0826",
        bookingNumber: "AIR-BKG-99381",
        documentNumber: "075-99381204",
        chargeCode: "BASIC_FREIGHT",
        description: "Flete Aéreo MAD -> MEX (320 kg)",
        billedQuantity: 320,
        billedRate: 4.9625,
        billedAmount: 1588.0,
        expectedQuantity: 320,
        expectedRate: 4.9625,
        expectedAmount: 1588.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
      // Road Invoice Line
      {
        id: "line_tie_01",
        carrierInvoiceId: "inv_tie_4412",
        bookingNumber: "ROAD-BKG-99210",
        documentNumber: "CMR-2026-99210",
        chargeCode: "BASIC_FREIGHT",
        description: "Transporte Terrestre FTL Madrid -> Lyon (33 Pallets)",
        billedQuantity: 1,
        billedRate: 1850.0,
        billedAmount: 1850.0,
        expectedQuantity: 1,
        expectedRate: 1850.0,
        expectedAmount: 1850.0,
        varianceAmount: 0.0,
        variancePercentage: 0.0,
        isWithinTolerance: true,
        disputeStatus: "NONE",
      },
    ])
    .onConflictDoNothing();

  console.log(
    "✅ Creados Tipos de Cambio FX, Posiciones de Tesorería y Facturas CASS / Navieras.",
  );
}
