name: njsscan sarif

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 17 * * 5'

permissions:
  contents: read

jobs:
  njsscan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    name: njsscan code scanning
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: nodejsscan scan
      run: pip install njsscan && njsscan . --sarif --output results.sarif || true
    - name: Upload njsscan report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif

